# Generated by Django 4.1.3 on 2022-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
