# Generated by Django 4.1.3 on 2022-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproyecto', '0002_familiar_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sextuples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('empresa_vp', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
