# Generated by Django 4.1.3 on 2022-12-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproyecto', '0004_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='empresa_vp',
        ),
    ]
